name: Dependency Review

on:
  pull_request:
    branches: [v2, v3]

permissions:
  contents: read

jobs:
  review:
    name: Review
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/dependency-review-action@v4
        with:
          fail-on-severity: moderate
