name: NPM Release

on:
  workflow_dispatch:

permissions:
  contents: write
  issues: write
  pull-requests: write
  id-token: write

jobs:
  ci:
    name: Pre-release checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Enable Corepack
        run: corepack enable

      - uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: yarn

      - name: Install
        run: yarn install --immutable

      - name: Type-check
        run: yarn tsc --noEmit

      - name: Build
        run: yarn build

      - name: Test
        run: yarn test

  release:
    name: NPM Release
    needs: ci
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Enable Corepack
        run: corepack enable

      - uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: yarn

      - name: Install
        run: yarn install --immutable

      - name: Build
        run: yarn build

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}